eyetracker.hw.sr_research.eyelink.EyeTracker:
  name: Soltani Eyelink 
  enable: True
  auto_report_events: False
  event_buffer_length: 2048
  device_timer:
    interval: 0.001
  monitor_event_types: [
    MonocularEyeSampleEvent,
    FixationStartEvent,
    FixationEndEvent,
    SaccadeStartEvent,
    SaccadeEndEvent
  ]
  calibration:
    type: NINE_POINTS
    auto_pace: True
    pacing_speed: 1.5
    screen_background_color: [128, 128, 128, 255]
    target_type: CIRCLE_TARGET
    target_attributes:
      outer_diameter: 33
      inner_diameter: 6
      outer_color: [255, 255, 255, 255]
      inner_color: [0, 0, 0, 255]
  network_settings: 100.1.1.1
  default_native_data_file_name: fips_saccade
  simulation_mode: True
  enable_interface_without_connection: False
  runtime_settings:
    sampling_rate: 1000
    track_eyes: RIGHT_EYE
    sample_filtering:
      FILTER_ALL: FILTER_LEVEL_1
    vog_settings:
      pupil_measure_types: PUPIL_DIAMETER
      tracking_mode: PUPIL_CR_TRACKING
      pupil_center_algorithm: ELLIPSE_FIT
  model_name: EYELINK 1000 DESKTOP